name: Docker Release

on:
  release:
    types:
      - published

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Docker Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
        timeout-minutes: 1
      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=10485760
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_HEALTHBOT_USER }}
          password: ${{ secrets.DOCKER_HUB_HEALTH_PASSWORD }}
      - name: Run build script
        run: ./docker/build.sh
        shell: bash